<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZCBLRLP0293" failures="4" tests="19" name="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" time="379.256" errors="0" timestamp="2024-07-11T21:35:37 IST" skipped="0">
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_NonEditable_LocationField" time="8.225"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_NonEditable_DateField" time="8.427"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_NonEditable_TimeField" time="7.793"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_EarnPoints_Navigation_From_MeberDetailsScreen" time="9.436"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_MemberDetails_Content_Displaying_On_EarnPointScreen" time="68.950">
    <failure message="An error occurred during Member details verification: Timeout waiting for elements." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: An error occurred during Member details verification: Timeout waiting for elements.
at org.testng.Assert.fail(Assert.java:111)
at zapcg.Capillary.PageObject.earnPointsPage.verifyTheMemberDetailsContentDisplaying(earnPointsPage.java:220)
at zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases.verify_MemberDetails_Content_Displaying_On_EarnPointScreen(EarnPoint_Valid_TestCases.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verify_MemberDetails_Content_Displaying_On_EarnPointScreen -->
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_HeaderHyperlink_On_EarnPoint_Page" time="8.659"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_BackButton_Navigation_On_EarnPoint_Page" time="8.275"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_Hamburger_MemberLookupOption_From_EarnPoint_Page" time="9.204"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_Hamburger_LocationOption_From_EarnPoint_Page" time="8.988"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_HamBurger_LogoutOption_From_EarnPoint_Page" time="12.194"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_Date_Equal_To_System_CurrentDate" time="8.216"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_Time_Equal_To_System_CurrentTime" time="8.188">
    <failure message="The time in the field should match the system time expected [21:32:03] but found [21:32:02]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The time in the field should match the system time expected [21:32:03] but found [21:32:02]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at zapcg.Capillary.PageObject.earnPointsPage.timeVerification(earnPointsPage.java:666)
at zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases.verify_Time_Equal_To_System_CurrentTime(EarnPoint_Valid_TestCases.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verify_Time_Equal_To_System_CurrentTime -->
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_With_Empty_TransactionAmount" time="8.190"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="empty_TxnAmount_But_GoToPassPoint_Value" time="8.929"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verifySuccessMessageForOnlyTransactionAmount" time="9.878"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_TaxAssumedAmount" time="7.967"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_SuccessMessage_For_RedeemPoint" time="98.736">
    <failure message="Timeout waiting for success message element." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Timeout waiting for success message element.
at org.testng.Assert.fail(Assert.java:111)
at zapcg.Capillary.PageObject.earnPointsPage.verifySuccessMessageIfRedeemingPoints(earnPointsPage.java:865)
at zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases.verify_SuccessMessage_For_RedeemPoint(EarnPoint_Valid_TestCases.java:231)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verify_SuccessMessage_For_RedeemPoint -->
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_Eligible_EarningPoints" time="8.306"/>
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases" name="verify_ExceedThresold_SuccessMessage" time="70.695">
    <failure message="Timeout waiting for success message element." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Timeout waiting for success message element.
at org.testng.Assert.fail(Assert.java:111)
at zapcg.Capillary.PageObject.earnPointsPage.verifySuccessMessageExceedThresoldValue(earnPointsPage.java:1011)
at zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases.verify_ExceedThresold_SuccessMessage(EarnPoint_Valid_TestCases.java:286)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verify_ExceedThresold_SuccessMessage -->
</testsuite> <!-- zapcg.Capillary.EarnPointPageTestCases.EarnPoint_Valid_TestCases -->
